#include "listadeprodutos.c"

int main() {
  PLISTA f = criarLista();
  bool res;

    printf("################# INSERINDO #######################\n");
    res = inserirNovoProduto(f,0,2,2,100);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,1,0,5,250);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,2,9,10,30);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,3,1,2,45);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,4,2,5,750);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,5,8,8,20);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,6,3,100,1);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,7,2,3,30);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,8,7,5,55);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,9,7,15,20);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,10,0,20,12);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,11,4,14,5);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,12,4,56,6);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,13,5,98,10);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,14,4,54,15);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,15,4,1,58);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,16,3,20,89);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,17,0,30,96);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,18,2,65,32);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,19,5,2,20);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,20,2,3,10);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,21,3,3,12);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,22,4,5,35);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,23,4,4,68);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,24,7,8,98);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,25,5,7,52);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,26,5,6,20);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,27,1,90,12);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,28,4,20,36);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,29,9,50,98);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,30,1,12,21);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,31,8,20,14);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,32,6,35,14);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,33,2,52,20);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,34,1,20,30);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,36,9,50,98);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,37,3,20,89);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,38,2,65,32);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,39,4,56,6);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,40,2,2,100);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,41,2,30,1);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,42,4,10,45);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,43,2,65,35);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f,44,3,25,20);
    if (res) printf("true\n");
    else printf("false\n");
    exibirLog(f);

    printf("################# REMOVENDO #######################\n");
    res = removerItensDeUmProduto(f,0,2);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,1,4);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,2,1);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,3,2);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,4,3);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,5,8);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,6,7);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,7,3);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,8,5);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,9,3);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,10,10);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,11,7);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,12,27);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,13,94);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,14,25);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,15,1);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,16,15);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,17,28);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,18,65);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,19,2);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,20,2);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,21,3);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,22,1);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,23,3);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,24,6);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,25,4);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,26,6);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,27,8);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,28,4);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,29,48);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,30,12);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,31,18);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,32,13);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,33,41);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,34,10);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,36,28);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,37,14);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,38,43);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,39,33);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,40,1);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,41,7);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,42,8);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,43,7);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f,44,21);
    if (res) printf("true\n");
    else printf("false\n");
    exibirLog(f);

    printf("################# ATUALIZANDO #######################\n");
    res = atualizarValorDoProduto(f, 0,96);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 1,63);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 2,25);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 3,24);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 4,546);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 5,6);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 6,1);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 7,29);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 8,2);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 9,12);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 10,2);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 11,5);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 12,6);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 13,5);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 14,13);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 15,44);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 16,12);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 17,95);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 18,27);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 19,14);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 20,6);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 21,12);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 22,17);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 23,60);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 24,1);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 25,6);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 26,10);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 27,7);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 28,19);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 29,28);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 30,2);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 31,2);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 32,14);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 33,8);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 34,20);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 36,24);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 37,30);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 38,25);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 39,3);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 40,81);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 41,1);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 42,14);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 43,16);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 44,13);
    if (res) printf("true\n");
    else printf("false\n");
    exibirLog(f);


    printf("################# CASOS PARTICULARES #######################\n");
    printf("# ALTERAR PRECO E QTD DO ITEM 9 PARA O MESMO VALOR TOTAL DO ITEM 24 -> DEVE SER REPOSICIONADO PARA ESQUERDA #\n");
    res = atualizarValorDoProduto(f, 9,1);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f, 9,10);
    if (res) printf("true\n");
    else printf("false\n");
    exibirLog(f);

    printf("# ALTERAR PRECO DO ITEM 2 PARA O VALOR TOTAL MAIOE Q DO ITEM 36 -> DEVE SER REPOSICIONADO PARA DIREITA #\n");
    res = atualizarValorDoProduto(f, 2,200);
    if (res) printf("true\n");
    else printf("false\n");
    exibirLog(f);

    printf("# ALTERAR PRECO DO ITEM 20 PARA O MAIOR VALOR TOTAL DA LISTA 2 -> DEVE SER REPOSICIONADO PARA O FINAL #\n");
    res = atualizarValorDoProduto(f, 20,2000);
    if (res) printf("true\n");
    else printf("false\n");
    exibirLog(f);

    printf("# ALTERAR PRECO DO ITEM 37 PARA O MENOR VALOR TOTAL DA LISTA 3 -> DEVE SER REPOSICIONADO PARA O COMECO #\n");
    res = atualizarValorDoProduto(f, 37,1);
    if (res) printf("true\n");
    else printf("false\n");
    exibirLog(f);

    printf("# REMOVER COMPLETAMENTE O ITEM 42 DA LISTA 4 -> O NOH CABECA TERA DE APONTAR PARA O SEGUNDO ITEM #\n");
    res = removerItensDeUmProduto(f, 42,2);
    if (res) printf("true\n");
    else printf("false\n");
    exibirLog(f);

    printf("# REMOVER PARTE DO ITEM O ITEM 28 DA LISTA 4 PARA FICAR IGUAL AO 22 \n");
    printf("E DEPOIS ALTERAR O PRECO PARA QUE O VALOR TOTAL FIQUE IGUAL AO ITEM 22 -> DEVE SER REPOSICIONADO PARA A ESQUERDA #\n");
    res = removerItensDeUmProduto(f, 28,12);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 28,17);
    if (res) printf("true\n");
    else printf("false\n");
    exibirLog(f);

    printf("################# CASOS DE ERRO ATUALIZAR PRODUTO (DEVEM RETORNAR FALSE) #######################\n");
    res = atualizarValorDoProduto(f, 0,1);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 100,1);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 10,0);
    if (res) printf("true\n");
    else printf("false\n");
    res = atualizarValorDoProduto(f, 32,-10);
    if (res) printf("true\n");
    else printf("false\n");

    printf("################# CASOS DE ERRO REMOVER ITENS PRODUTO (DEVEM RETORNAR FALSE) #######################\n");
    res = removerItensDeUmProduto(f, 0,12);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f, 100,12);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f, 10,120);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f, 31,-12);
    if (res) printf("true\n");
    else printf("false\n");
    res = removerItensDeUmProduto(f, 11,0);
    if (res) printf("true\n");
    else printf("false\n");

    printf("################# CASOS DE ERRO INSERIR PRODUTOS (DEVEM RETORNAR FALSE) #######################\n");
    res = inserirNovoProduto(f, -1,0,1,12);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f, 10,0,1,12);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f, 50,10,1,12);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f, 50,9,0,12);
    if (res) printf("true\n");
    else printf("false\n");
    res = inserirNovoProduto(f, 50,9,2,0);
    if (res) printf("true\n");
    else printf("false\n");

    exibirLog(f);

    printf("Tamanho lista: %i",tamanho(f));

    return 0;
}